// Assignment: Use JavaScript to generate password with user prompts.

// JavaScript provided in assignment, connected to HTML Generate Password
var generateBtn = document.querySelector("#generate");

// Starting Data (initialization)

// Character banks: Variables with .split(""); function to create arrays
var alphabetLowercase = "abcdefghijklmnopqrstuvwxyz".split("");
// Console log to check function (which I'll add to each Var)
console.log(alphabetLowercase);

var alphabetCaps = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");
console.log(alphabetCaps);

var num = "1234567890".split("");
console.log(num);

var sym = "~!@#$%^&*<>?()+=:;,.".split("");
console.log(sym);

var majorBank = "~!@#$%^&*<>?()+=:;,1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".split(
  ""
);
console.log(majorBank);

// Updating data based on user data

// Generate password to connect to Var, prompted by User Input

// lowercase
// uppercase
// numbers
// at least one symbol (special characters)
// function will pull arguments from higher scope, not in the function below

function generatePassword() {
  var passwordLength;
  passwordLength = prompt(
    "Enter a number between 8 and 128. This will determine your password length"
  );
  if (passwordLength > 128 || passwordLength < 8) {
    alert(
      "Try again. Please enter any number between numbers 8 and 128. From there, we'll continue a few more prompts."
    );
    return generatePassword();
  }
  //entering Var to keep prompts to 1 occurance.
  var numbers = false;
  var symbols = false;
  var caps = false;
  var lowercase = false;
  var confirms = 0;

  // New Password will be generated by randomly selected characters.
  var newPassword = [];

  //setting the conditions for each Var
  // If true must contain at least one of
  // if true add one from the array or string from each character bank
  // counter of # of confirms, checks to see of var numbers, symbols, caps, lowercase is true, and if true ads one of that particular element to the password length
  // Set to false as default but if user presses ok it will change value to true used in "if" statements
  numbers = confirm("Do you want numbers in your password?");
  console.log(numbers);
  symbols = confirm("Do you want symbols in your password?");
  console.log(symbols);
  caps = confirm("Do you want caps in your password?");
  console.log(caps);
  lowercase = confirm("Do you want lowercase in your password?");
  console.log(lowercase);

  //inserting MathRandom to generate number from our bank
  if (numbers) {
    confirms = confirms + 1;
  }
  if (symbols) {
    confirms = confirms + 1;
  }
  if (caps) {
    confirms = confirms + 1;
  }
  if (lowercase) {
    confirms = confirms + 1;
  }
  console.log(confirm);
  // Adding onditionals to randomly pull from each of the four banks and pushed to end of newPassword
  if (numbers) {
    newPassword.push(num[randomPull(num)]);
  }
  if (symbols) {
    newPassword.push(sym[randomPull(sym)]);
  }
  if (caps) {
    newPassword.push(alphabetCaps[randomPull(alphabetCaps)]);
  }
  if (lowercase) {
    newPassword.push(alphabetLowercase[randomPull(alphabetLowercase)]);
  }
  console.log(newPassword);

  //For loop Must include (at a min) one character from each bank,
  // for finding the number of times to pull from the majorBank
  // which is a minimum of 8 characters

  for (var i = 0; i < passwordLength - confirms; i++) {
    newPassword.unshift(majorBank[randomPull(majorBank)]);
  }
  // Array of newPassword
  console.log(newPassword);

  newPassword = newPassword.join("");

  // String of newPassword
  console.log(newPassword);
  return newPassword;
}
// string is a parameter or placeholder for what you will put in when you add anything with a length property
function randomPull(string) {
  return Math.floor(Math.random() * string.length);
}
function writePassword() {
  var password = generatePassword();
  var passwordText = document.querySelector("#password");
  passwordText.value = password;
}
// create a function called generatepassword

// Add event listener to generate button
generateBtn.addEventListener("click", writePassword);
