// Assignment: Use JavaScript to generate password with user prompts.

// JavaScript provided in assignment, connected to HTML Generate Password
var generateBtn = document.querySelector("#generate");

          // Starting Data (initialization)

// Character banks: Variables with .split(""); function to create arrays
var alphabetLowercase = "abcdefghijklmnopqrstuvwxyz".split("");
// Console log to check function (which I'll add to each Var)
console.log(alphabetLowercase);

var alphabetCaps = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");
console.log(alphabetCaps);

var num = "1234567890".split("");
console.log(num);

var sym = "~!@#$%^&*<>?()+=:;,.".split("");
console.log(sym);

var majorBank = "~!@#$%^&*<>?()+=:;,1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".split(
  ""
);
console.log(majorBank);

          // Updating data based on user data

// Generate password to connect to Var, prompted by User Input

// lowercase
// uppercase
// numbers
// at least one symbol (special characters)
// function will pull arguments from higher scope, not in the function below

function generatePassword() {
  var passwordLength;
  passwordLength = prompt("Enter a number between 8 and 128. This will determine your password length");
  if (passwordLength > 128 || passwordLength < 8) {
    alert(
      "Try again. Please enter any number between numbers 8 and 128. From there, we'll continue a few more prompts."
    );
    return generatePassword();
  }
  //entering Var to keep prompts to 1 occurance.
  var numbers = false;
  var symbols = false;
  var caps = false;
  var lowercase = false;
  var confirms = 0;

  // New Password will be generated by randomly selected characters.
  var newPassword = [];
